insert into hrtm.teams
(id, name, created_at, updated_at) VALUES
(1, 'HR-ITALY', now(), now()),
(2, 'HR-SPAIN', now(), now()),
(3, 'HR-ECUADOR', now(), now()),
(4, 'HR-SUISSE', now(), now()),
(5, 'HR-ISRAEL', now(), now()),
(6, 'HR-CHINA', now(), now()),
(7, 'HR-US', now(), now()),
(8, 'HR-DOTS', now(), now()),
(9, 'HR-DEUTSCHLAND', now(), now()),
(10, 'HR-MEXICO', now(), now()),
(11, 'HR-BRAZIL', now(), now()),
(12, 'HR-JAPAN', now(), now()),
(13, 'HR-RUSSIA', now(), now()),
(14, 'HR-INDIA', now(), now()),
(15, 'HR-POLAND', now(), now()),
(16, 'HR-BELGIUM', now(), now()),
(19, 'HR-UK', now(), now()),
(22, 'HR-FRANCE', now(), now()),
(25, 'HR-AUSTRALIA', now(), now()),
(26, 'HR-MALTA', now(), now()),
(27, 'HR-GQC', now(), now()),
(28, 'HR-ARGENTINA', now(), now());